### ISSUE TITLE
Support for non-suspeneded APIs

### ISSUE THREAD

**Issue by SaeedZhiany** [xxfast/KStore#127] opened 2024-09-24 11:08 UTC
all APIs from this library are suspended. what is the reason?
is it possible to have non-suspended APIs too?

Thanks

**Comment by xxfast** [comment] 2024-09-25 03:30
Hi @SaeedZhiany 

This is by design.

KStore guarantees synchronisation with [Mutex](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.sync/-mutex/) locks. This allows stores to be written from multiple coroutines whilst retaining the written order (See [this test case](https://github.com/xxfast/KStore/blob/master/kstore/src/commonTest/kotlin/io/github/xxfast/kstore/KStoreTests.kt#L149) as an example)

On top of all that - writes/reads to/from the disk will always blocks the thread you call it from. KStore internally uses `Dispatcher.IO` to make sure `Dispatcher.Main` is not blocked (which is often used for rendering) 

Whats your use case for non-suspended API?

**Comment by xxfast** [comment] 2024-10-24 06:18
Closing this issue for now. Feel free to comment if you have more input

**Closed by xxfast** 2024-10-24 06:18 UTC
